const CELEBRATION_EVENTS = [
  {
    id: "new-game-plus",
    name: "New Game Plus",
    startMonth: 1,
    startDay: 1,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🎮",
    bannerTitle: "New Game Plus",
    bannerSubtitle: "Every beginning is not an empty page, but a wiser return to the first step.",
    description: "A symbolic reset for carrying old lessons into new quests, with brighter intent and quieter courage.",
  },
  {
    id: "blue-monday-reframe",
    name: "Blue Monday Reframe",
    dateRule: "third-monday-of-january",
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🌧️",
    bannerTitle: "Soft Reset",
    bannerSubtitle: "Heavy days do not define the season; they ask for gentleness, patience, and one small next step.",
    description: "A compassionate reframe of a difficult winter moment, centered on care, rest, and realistic hope.",
  },
  {
    id: "world-compliment-day",
    name: "World Compliment Day",
    startMonth: 3,
    startDay: 1,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "💬",
    bannerTitle: "Words That Lift",
    bannerSubtitle: "A sincere compliment is a mirror briefly held up to someone’s hidden effort.",
    description: "A positive theme about recognition, encouragement, gratitude, and the small sentences that help people keep going.",
  },
  {
    id: "world-sleep-day",
    name: "World Sleep Day",
    dateRule: "friday-before-march-equinox",
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "🌙",
    bannerTitle: "Rest Ritual",
    bannerSubtitle: "Rest is not a pause from becoming; it is one of the ways becoming stays possible.",
    description: "A calm, night-toned celebration of recovery, rhythm, nervous systems, and the wisdom of slowing down.",
  },
  {
    id: "world-creativity-and-innovation-day",
    name: "World Creativity and Innovation Day",
    startMonth: 4,
    startDay: 21,
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "💡",
    bannerTitle: "Unmade Paths",
    bannerSubtitle: "Innovation begins where curiosity refuses to accept that the current shape is the only possible one.",
    description: "An inventive celebration of experimentation, imagination, better questions, and the brave disorder before new solutions.",
  },
  {
    id: "workers-day",
    name: "Workers' Day",
    startMonth: 5,
    startDay: 1,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🛠️",
    bannerTitle: "Hands That Build",
    bannerSubtitle: "Every society rests on visible and invisible labor, and dignity belongs to both.",
    description: "A respectful celebration of work, craft, fairness, solidarity, and the people whose effort keeps the world moving.",
  },
  {
    id: "world-blood-donor-day",
    name: "World Blood Donor Day",
    startMonth: 6,
    startDay: 14,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🩸",
    bannerTitle: "Shared Pulse",
    bannerSubtitle: "To give life quietly is one of humanity’s most practical forms of hope.",
    description: "A respectful theme honoring donors, healthcare, solidarity, and the unseen generosity that keeps strangers alive.",
  },
  {
    id: "sysadmin-day",
    name: "System Administrator Appreciation Day",
    dateRule: "last-friday-of-july",
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🖥️",
    bannerTitle: "Keepers of Uptime",
    bannerSubtitle: "The most reliable magic is often invisible because someone prepared before the storm arrived.",
    description:
      "A tech-themed tribute to infrastructure, reliability, quiet expertise, incident response, and the people who keep systems alive.",
  },
  {
    id: "moomin-day",
    name: "Moomin Day",
    startMonth: 8,
    startDay: 9,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌙",
    bannerTitle: "Moominvalley Day",
    bannerSubtitle: "Not every adventure needs a battle; some begin with tea, silence, and the decision to welcome the unknown.",
    description:
      "The page becomes a quiet valley of wonder, friendship, tolerance, homesickness, and small brave journeys beneath a Nordic sky.",
  },
  {
    id: "pretend-to-be-a-time-traveler-day",
    name: "Pretend to Be a Time Traveler Day",
    startMonth: 12,
    startDay: 8,
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "⏳",
    bannerTitle: "Temporal Visitor",
    bannerSubtitle: "Imagining another time helps us see the present as something strange, temporary, and still changeable.",
    description: "A playful philosophical theme about perspective, history, futures, imagination, and the weirdness of now.",
  },
  {
    id: "world-smile-day",
    name: "World Smile Day",
    dateRule: "first-friday-of-october",
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "🙂",
    bannerTitle: "A Brief Brightness",
    bannerSubtitle: "A smile cannot solve everything, but it can remind someone they are still seen.",
    description: "A light, human theme about warmth, approachability, kindness, and the quiet social power of small gestures.",
  },
  {
    id: "international-coffee-day",
    name: "International Coffee Day",
    startMonth: 10,
    startDay: 1,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "☕",
    bannerTitle: "First Sip Focus",
    bannerSubtitle: "Some rituals are small machines of meaning, turning pause into readiness.",
    description: "A cozy celebration of daily rituals, warmth, craft, conversation, and the thoughtful energy of a fresh beginning.",
  },
  {
    id: "international-yoga-day",
    name: "International Yoga Day",
    startMonth: 6,
    startDay: 21,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🧘‍♀️",
    bannerTitle: "Body as Compass",
    bannerSubtitle: "The body is not a machine to conquer, but a companion that teaches balance through attention.",
    description: "A mindful theme about movement, breath, discipline, embodiment, and the quiet alignment of strength and softness.",
  },
  {
    id: "constitution-day-pl",
    name: "Constitution Day (Poland)",
    startMonth: 5,
    startDay: 3,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "📜",
    bannerTitle: "Civic Chronicle",
    bannerSubtitle: "A wise law is not only ink on paper; it is a promise that power should answer to people.",
    description: "A dignified civic theme about responsibility, memory, public life, and the fragile craft of shared governance.",
  },
  {
    id: "international-day-of-happiness",
    name: "International Day of Happiness",
    startMonth: 3,
    startDay: 20,
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "😊",
    bannerTitle: "Joy With Roots",
    bannerSubtitle: "Happiness grows deeper when it is shared, protected, and allowed to coexist with truth.",
    description: "A bright but grounded theme about meaning, connection, gratitude, and joy that does not require denial.",
  },
  {
    id: "world-wildlife-day",
    name: "World Wildlife Day",
    startMonth: 3,
    startDay: 3,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🦊",
    bannerTitle: "Wild Kinship",
    bannerSubtitle: "The wild world is not outside our story; it is one of the oldest chapters we still depend on.",
    description: "A nature-centered theme honoring biodiversity, coexistence, conservation, and the fragile intelligence of ecosystems.",
  },
  {
    id: "random-acts-of-kindness-day",
    name: "Random Acts of Kindness Day",
    startMonth: 2,
    startDay: 17,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌼",
    bannerTitle: "Unplanned Goodness",
    bannerSubtitle: "The most powerful kindness often arrives without ceremony, changing the temperature of an ordinary day.",
    description: "A warm reminder that small, spontaneous gestures can soften systems, relationships, and the inner weather of others.",
  },
  {
    id: "world-hug-day",
    name: "World Hug Day",
    startMonth: 1,
    startDay: 21,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🤗",
    bannerTitle: "Warm Distance Closed",
    bannerSubtitle: "Connection is sometimes the quiet message that says: you do not have to carry this alone.",
    description: "A gentle celebration of closeness, comfort, emotional safety, and the human need to be held by presence.",
  },
  {
    id: "world-logic-day",
    name: "World Logic Day",
    startMonth: 1,
    startDay: 14,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🧠",
    bannerTitle: "Logic Lantern",
    bannerSubtitle: "Clear thinking is a small light that can guide us through very large unknowns.",
    description: "A reflective celebration of reason, patterns, careful questions, and the quiet beauty of structured thought.",
  },
  {
    id: "international-education-day",
    name: "International Day of Education",
    startMonth: 1,
    startDay: 24,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "🎓",
    bannerTitle: "Path of Learning",
    bannerSubtitle: "Knowledge is not a trophy we collect, but a door we learn how to open for others.",
    description: "The interface honors learning as a shared journey, where curiosity becomes skill and skill becomes possibility.",
  },
  {
    id: "data-privacy-day",
    name: "Data Privacy Day",
    startMonth: 1,
    startDay: 28,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🔐",
    bannerTitle: "Privacy Shield",
    bannerSubtitle: "What we protect reveals what we value; privacy is dignity expressed in design.",
    description: "A calm, thoughtful theme focused on trust, boundaries, digital responsibility, and respectful technology.",
  },
  {
    id: "valentines-day",
    name: "Valentine's Day",
    startMonth: 2,
    startDay: 14,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "❤️",
    bannerTitle: "Heartlight Day",
    bannerSubtitle: "Love is not only a spark; it is the patient warmth that teaches us to stay human.",
    description: "A gentle celebration of care, gratitude, friendship, tenderness, and the small gestures that make life softer.",
  },
  {
    id: "world-kindness-day-alt",
    name: "Small Kindness Day",
    startMonth: 2,
    startDay: 17,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🤝",
    bannerTitle: "Kindness Echo",
    bannerSubtitle: "A kind act rarely ends where it begins; it travels farther than we can measure.",
    description: "The page carries a warm, humane tone, reminding users that small compassion can shift the atmosphere around it.",
  },
  {
    id: "international-womens-day",
    name: "International Women's Day",
    startMonth: 3,
    startDay: 8,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌸",
    bannerTitle: "Strength in Bloom",
    bannerSubtitle: "Progress grows where courage is remembered, voices are heard, and dignity is never optional.",
    description:
      "A respectful celebration of resilience, equality, creativity, leadership, and the generations who moved the world forward.",
  },
  {
    id: "pi-day",
    name: "Pi Day",
    startMonth: 3,
    startDay: 14,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "π",
    bannerTitle: "Circle of Wonder",
    bannerSubtitle: "Some truths are endless, reminding us that mystery can live inside precision.",
    description: "A playful but thoughtful math-inspired celebration of patterns, infinity, curiosity, and elegant complexity.",
  },
  {
    id: "spring-equinox",
    name: "Spring Equinox",
    startMonth: 3,
    startDay: 20,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🌱",
    bannerTitle: "Balance in Bloom",
    bannerSubtitle: "When light and shadow stand equal, growth quietly chooses its direction.",
    description: "A seasonal transition theme about renewal, balance, patience, and the fragile beginnings of meaningful change.",
  },
  {
    id: "world-poetry-day",
    name: "World Poetry Day",
    startMonth: 3,
    startDay: 21,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "🖋️",
    bannerTitle: "Words Beneath Words",
    bannerSubtitle: "Poetry reminds us that language is not only a tool, but a place where meaning learns to breathe.",
    description: "A lyrical celebration of metaphor, silence, emotion, and the hidden depth carried by carefully chosen words.",
  },
  {
    id: "april-fools",
    name: "April Fools' Day",
    startMonth: 4,
    startDay: 1,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🃏",
    bannerTitle: "Trickster Mode",
    bannerSubtitle: "Wisdom needs seriousness, but it also needs laughter to keep from becoming stone.",
    description: "A lighthearted celebration of surprise, humor, harmless mischief, and the useful humility of being fooled.",
  },
  {
    id: "world-health-day",
    name: "World Health Day",
    startMonth: 4,
    startDay: 7,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🫀",
    bannerTitle: "Quiet Strength",
    bannerSubtitle: "Health is not merely the absence of pain, but the presence of care, rhythm, and recovery.",
    description: "A grounded, calming theme that honors rest, resilience, bodies, minds, and the systems that help people heal.",
  },
  {
    id: "earth-day",
    name: "Earth Day",
    startMonth: 4,
    startDay: 22,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🌍",
    bannerTitle: "Earth Day Grove",
    bannerSubtitle: "We do not stand above the earth; we stand within its patience, borrowed breath, and fragile abundance.",
    description: "A green, ecology-forward celebration of interdependence, responsibility, and the quiet intelligence of living systems.",
  },
  {
    id: "world-book-day",
    name: "World Book Day",
    startMonth: 4,
    startDay: 23,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "📚",
    bannerTitle: "Library Quest",
    bannerSubtitle: "A book is a lantern carried by someone you may never meet, lighting a road you have not yet walked.",
    description: "The page becomes a literary map of memory, imagination, inherited wisdom, and worlds hidden between pages.",
  },
  {
    id: "star-wars-day",
    name: "Star Wars Day",
    startMonth: 5,
    startDay: 4,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "✨",
    bannerTitle: "Galactic Quest",
    bannerSubtitle: "Even among distant stars, the oldest battle is still the one between fear and hope.",
    description: "A cosmic adventure mood celebrating myth, courage, mentorship, destiny, and the strange gravity of choice.",
  },
  {
    id: "mothers-day-global",
    name: "Mother's Day (Global)",
    dateRule: "second-sunday-of-may",
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌷",
    bannerTitle: "Mother's Day",
    bannerSubtitle: "Some love teaches without speaking, protects without applause, and remains long after the moment has passed.",
    description: "A tender celebration of care, sacrifice, guidance, memory, and the many forms that motherly love can take.",
  },
  {
    id: "mothers-day-pl",
    name: "Mother's Day (Poland)",
    startMonth: 5,
    startDay: 26,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌷",
    bannerTitle: "Mother's Day",
    bannerSubtitle: "The deepest roots are often invisible, yet they hold entire lives upright.",
    description: "A warm Polish Mother’s Day theme honoring gratitude, family bonds, quiet strength, and everyday devotion.",
  },
  {
    id: "children-day-pl",
    name: "Children's Day (Poland)",
    startMonth: 6,
    startDay: 1,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🧸",
    bannerTitle: "Wonder Day",
    bannerSubtitle: "Childhood reminds us that wonder is not a phase, but a way of seeing before the world teaches us to hurry.",
    description: "A bright and gentle celebration of play, imagination, safety, curiosity, and the wisdom hidden in simple questions.",
  },
  {
    id: "world-environment-day",
    name: "World Environment Day",
    startMonth: 6,
    startDay: 5,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🌿",
    bannerTitle: "Living Systems",
    bannerSubtitle: "The future is not inherited fully formed; it is cultivated by what we choose not to ignore.",
    description: "A reflective green theme about stewardship, climate awareness, ecosystems, and responsibility toward what sustains us.",
  },
  {
    id: "fathers-day-pl",
    name: "Father's Day (Poland)",
    startMonth: 6,
    startDay: 23,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌷",
    bannerTitle: "Father's Day",
    bannerSubtitle: "Guidance is sometimes a hand on the shoulder, and sometimes the courage to let someone walk alone.",
    description: "A thoughtful Father’s Day celebration of support, patience, protection, humor, and lessons passed through presence.",
  },
  {
    id: "summer-solstice",
    name: "Summer Solstice",
    startMonth: 6,
    startDay: 21,
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "☀️",
    bannerTitle: "Sunlit Quest",
    bannerSubtitle: "At the height of light, we remember that brightness is most meaningful when it helps something grow.",
    description: "The alerts page turns golden and spacious, celebrating energy, openness, warmth, and the courage to be fully alive.",
  },
  {
    id: "friendship-day",
    name: "Friendship Day",
    startMonth: 7,
    startDay: 30,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🫶",
    bannerTitle: "Fellow Travelers",
    bannerSubtitle: "Friendship is the rare map drawn together while both travelers are still discovering the road.",
    description: "A warm social celebration of trust, shared stories, mutual growth, loyalty, and being witnessed without performance.",
  },
  {
    id: "international-youth-day",
    name: "International Youth Day",
    startMonth: 8,
    startDay: 12,
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "🚀",
    bannerTitle: "Future Sparks",
    bannerSubtitle: "Youth is not only age; it is the force that asks why the world cannot become kinder, braver, and wiser.",
    description:
      "An optimistic theme honoring young voices, fresh ideas, restless imagination, and the responsibility to make room for them.",
  },
  {
    id: "back-to-school",
    name: "Back to School",
    startMonth: 9,
    startDay: 1,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "✏️",
    bannerTitle: "Quest Log Reset",
    bannerSubtitle: "Learning begins again whenever humility meets curiosity and decides to continue.",
    description: "The alerts UI feels like the start of a new campaign chapter, full of tools, questions, and quiet determination.",
  },
  {
    id: "international-literacy-day",
    name: "International Literacy Day",
    startMonth: 9,
    startDay: 8,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "📖",
    bannerTitle: "Letters Become Roads",
    bannerSubtitle: "To read is to inherit more than words; it is to receive keys to rooms inside the world.",
    description: "A meaningful celebration of literacy, access to knowledge, self-expression, education, and the dignity of understanding.",
  },
  {
    id: "programmers-day",
    name: "Programmers' Day",
    startMonth: 9,
    startDay: 13,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "💻",
    bannerTitle: "Code & Consequence",
    bannerSubtitle: "Every line of code is a small decision about how reality should behave for someone else.",
    description: "A developer-minded celebration of craft, abstraction, debugging, responsibility, and the hidden humanity inside systems.",
  },
  {
    id: "autumn-equinox",
    name: "Autumn Equinox",
    startMonth: 9,
    startDay: 22,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🍂",
    bannerTitle: "Harvest Balance",
    bannerSubtitle: "When the year exhales, it teaches us that letting go can also be a form of wisdom.",
    description: "A reflective seasonal theme about balance, harvest, maturity, release, and the beauty of transitions.",
  },
  {
    id: "world-mental-health-day",
    name: "World Mental Health Day",
    startMonth: 10,
    startDay: 10,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🕯️",
    bannerTitle: "Inner Weather",
    bannerSubtitle: "Not every storm is visible, and not every victory is loud enough for others to notice.",
    description: "A quiet, respectful theme centered on care, emotional honesty, support, rest, and the courage to ask for help.",
  },
  {
    id: "teachers-day-pl",
    name: "Teacher's Day (Poland)",
    startMonth: 10,
    startDay: 14,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "🍎",
    bannerTitle: "Mentor's Lantern",
    bannerSubtitle: "A good teacher does not only deliver answers; they protect the flame of asking better questions.",
    description: "A gratitude-focused celebration of mentors, educators, patience, guidance, and the long echo of meaningful teaching.",
  },
  {
    id: "halloween",
    name: "Halloween",
    startMonth: 10,
    startDay: 31,
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "🎃",
    bannerTitle: "Shadow Festival",
    bannerSubtitle: "Sometimes we wear masks not to hide the truth, but to safely meet the shadows we carry.",
    description: "A mysterious seasonal mood exploring fear, play, folklore, transformation, and the strange comfort of darkness.",
  },
  {
    id: "all-saints-day-pl",
    name: "All Saints' Day (Poland)",
    startMonth: 11,
    startDay: 1,
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "🕯️",
    bannerTitle: "Memory Lights",
    bannerSubtitle: "To remember is to keep a small flame alive against the vastness of absence.",
    description: "A solemn and respectful theme of memory, continuity, gratitude, silence, and honoring those who came before us.",
  },
  {
    id: "independence-day-pl",
    name: "Independence Day (Poland)",
    startMonth: 11,
    startDay: 11,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🇵🇱",
    bannerTitle: "Freedom Chronicle",
    bannerSubtitle: "Freedom is not only won in history; it is renewed in responsibility, memory, and everyday courage.",
    description:
      "A dignified national theme reflecting independence, resilience, shared identity, and the duty to protect what was rebuilt.",
  },
  {
    id: "world-kindness-day",
    name: "World Kindness Day",
    startMonth: 11,
    startDay: 13,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "💛",
    bannerTitle: "Gentle Impact",
    bannerSubtitle: "Kindness is strength with its hands open, changing the world without needing to conquer it.",
    description: "A humane celebration of empathy, generosity, small gestures, and the invisible architecture of a better day.",
  },
  {
    id: "international-mens-day",
    name: "International Men's Day",
    startMonth: 11,
    startDay: 19,
    durationDays: 1,
    themeKey: "quest-log",
    emoji: "🛡️",
    bannerTitle: "Quiet Courage",
    bannerSubtitle: "Strength becomes wisdom when it learns to protect, listen, heal, and grow.",
    description:
      "A thoughtful celebration of responsibility, emotional maturity, positive role models, support, and healthier definitions of strength.",
  },
  {
    id: "winter-solstice",
    name: "Winter Solstice",
    startMonth: 12,
    startDay: 21,
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "🌑",
    bannerTitle: "Longest Night",
    bannerSubtitle: "Even the deepest dark is not the end of light, but the place where its return begins.",
    description: "A calm, mythic winter theme about endurance, reflection, stillness, hope, and the slow turning back toward brightness.",
  },
  {
    id: "winter-holidays",
    name: "Winter Holidays",
    startMonth: 12,
    startDay: 24,
    durationDays: 3,
    themeKey: "winter-legend",
    emoji: "❄️",
    bannerTitle: "Winter Legend Week",
    bannerSubtitle: "At the edge of the year, we gather warmth from memory, kindness, and the stories we choose to keep.",
    description: "The page glows with a holiday-fantasy mood, wrapping the year in gratitude, reflection, softness, and shared light.",
  },
  {
    id: "new-years-eve",
    name: "New Year's Eve",
    startMonth: 12,
    startDay: 31,
    durationDays: 1,
    themeKey: "sunlit-quest",
    emoji: "🎆",
    bannerTitle: "Final Save Point",
    bannerSubtitle: "Endings are not failures of permanence; they are invitations to carry meaning forward.",
    description:
      "A reflective year-end celebration of closure, gratitude, lessons learned, release, and the brave uncertainty of tomorrow.",
  },
  {
    id: "alice-in-wonderland-day",
    name: "Alice in Wonderland Day",
    startMonth: 7,
    startDay: 4,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🕳️",
    bannerTitle: "Down the Rabbit Hole",
    bannerSubtitle: "Wonder begins when logic loosens its grip and the impossible asks to be taken seriously.",
    description:
      "A surreal storybook celebration of curiosity, nonsense, identity, strange rules, and the courage to question the world’s shape.",
  },
  {
    id: "winnie-the-pooh-day",
    name: "Winnie-the-Pooh Day",
    startMonth: 1,
    startDay: 18,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🍯",
    bannerTitle: "Hundred Acre Wisdom",
    bannerSubtitle: "The gentlest friendships often teach the deepest lessons: stay close, speak simply, and share the honey.",
    description: "A warm celebration of friendship, innocence, small comforts, loyalty, and the quiet philosophy of being together.",
  },
  {
    id: "tolkien-reading-day",
    name: "Tolkien Reading Day",
    startMonth: 3,
    startDay: 25,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "🧙",
    bannerTitle: "Roads Go Ever On",
    bannerSubtitle: "Even the smallest traveler can carry a light strong enough to trouble the dark.",
    description: "A mythic literary celebration of fellowship, courage, language, loss, hope, and the long road toward impossible good.",
  },
  {
    id: "hobbit-day",
    name: "Hobbit Day",
    startMonth: 9,
    startDay: 22,
    durationDays: 1,
    themeKey: "festival-grove",
    emoji: "🍃",
    bannerTitle: "Second Breakfast Festival",
    bannerSubtitle: "Peace is worth defending because ordinary joys — gardens, songs, meals, and friends — are never ordinary at all.",
    description:
      "A cozy fantasy celebration of home, friendship, simple pleasures, courage, and the humble things that make life worth protecting.",
  },
  {
    id: "little-prince-day",
    name: "The Little Prince Day",
    startMonth: 6,
    startDay: 29,
    durationDays: 1,
    themeKey: "storybook-bloom",
    emoji: "🌹",
    bannerTitle: "Rose and Star",
    bannerSubtitle: "What matters most is often invisible, but it leaves its shape in every act of care.",
    description:
      "A tender philosophical celebration of friendship, responsibility, loneliness, wonder, and the fragile bonds that make planets feel like home.",
  },
  {
    id: "lovecraft-day",
    name: "Lovecraftian Mythos Day",
    startMonth: 8,
    startDay: 20,
    durationDays: 1,
    themeKey: "winter-legend",
    emoji: "🐙",
    bannerTitle: "At the Edge of Knowing",
    bannerSubtitle: "There are doors the mind can open only by admitting it was never the center of the universe.",
    description:
      "A cosmic-horror inspired mood of ancient mysteries, forbidden knowledge, fragile certainty, and the vertigo of the unknowable.",
  },
  {
    id: "pratchett-day",
    name: "Terry Pratchett Day",
    startMonth: 4,
    startDay: 28,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "🐢",
    bannerTitle: "Discworld Wisdom",
    bannerSubtitle: "Satire is kindness with sharp edges, cutting through nonsense so humanity can breathe again.",
    description:
      "A witty fantasy celebration of absurdity, justice, compassion, systems, stories, and the stubborn decency of ordinary people.",
  },
  {
    id: "neil-gaiman-day",
    name: "Neil Gaiman Day",
    startMonth: 11,
    startDay: 10,
    durationDays: 1,
    themeKey: "library-quest",
    emoji: "📚",
    bannerTitle: "Stories and Shadows",
    bannerSubtitle: "Imagination is the key to worlds unseen and tales untold.",
    description: "A literary celebration of storytelling, creativity, and the power of imagination.",
  },
];

module.exports = {
  CELEBRATION_EVENTS,
};
