blank_issues_enabled: true
contact_links:
  - name: Dołącz do naszego Discorda
    url: https://jaktestowac.pl/discord
    about: Zadawaj pytania i dyskutuj z innymi członkami społeczności AI, Automatyzacja i Playwright Polska
  - name: Poznaj AI w Automatyzacji
    url: https://aitesters.pl/
    about: Zdobądź przewagę łącząc wiedzę AI z najpopularniejszymi narzędziami na rynku IT.
